// Photos for /bday2026.
//
// Generated by scripts/gen-bday2026-manifest.py from public/bday2026/.
// Re-run that script after adding photos; captions you have already written
// are preserved by filename.

export type Photo = {
  src: string;
  /** Not shown on the page; this is the screen-reader description. */
  alt: string;
  /** Wider-than-tall photos get a landscape frame instead of the 3:4 one. */
  landscape?: boolean;
};

export const USING_PLACEHOLDERS = false;

export const PHOTOS: Photo[] = [
  {
    src: '/bday2026/01-golden-field.jpg',
    alt: 'Melisa in a white dress in a golden field at dusk',
  },
  {
    src: '/bday2026/02-night-lights.jpg',
    alt: 'The two of us together under warm evening lights',
    landscape: true,
  },
  {
    src: '/bday2026/03-kitten.jpg',
    alt: 'Melisa laughing, holding a tiny kitten',
  },
  {
    src: '/bday2026/04-bench.jpg',
    alt: 'The two of us sitting together on a wooden bench',
  },
  {
    src: '/bday2026/05-candlelight.jpg',
    alt: 'Melisa smiling across a candlelit table',
  },
  {
    src: '/bday2026/06-garden.jpg',
    alt: 'The two of us in a sunlit garden under an olive tree',
  },
  {
    src: '/bday2026/07-brick-wall.jpg',
    alt: 'Melisa in sunglasses against a pale brick wall',
  },
  {
    src: '/bday2026/08-together.jpg',
    alt: 'The two of us side by side, laughing',
  },
  {
    src: '/bday2026/09-beach-sunset.jpg',
    alt: 'Melisa on the beach at sunset in a pink dress',
  },
  {
    src: '/bday2026/hero-olive-grove.jpg',
    alt: 'An olive grove above the sea at sunset',
    landscape: true,
  },
];
