#!/usr/bin/env python3
"""Rebuild app/bday2026/photos.ts from whatever is in public/bday2026/.

Drop the "2032" album into public/bday2026/ and run:

    python3 scripts/gen-bday2026-manifest.py

Existing captions are preserved by filename, so you can re-run this after
adding more photos without losing the ones you already wrote.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PHOTO_DIR = ROOT / "public" / "bday2026"
MANIFEST = ROOT / "app" / "bday2026" / "photos.ts"
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".avif"}

HEADER = '''// Photos for /bday2026.
//
// Generated by scripts/gen-bday2026-manifest.py from public/bday2026/.
// Re-run that script after adding photos; captions you have already written
// are preserved by filename.

export type Photo = {
  src: string;
  alt: string;
  /** Little line shown under the photo. Leave undefined for no caption. */
  caption?: string;
};

export const USING_PLACEHOLDERS = false;

export const PHOTOS: Photo[] = [
'''


def existing_captions() -> dict[str, str]:
    if not MANIFEST.exists():
        return {}
    text = MANIFEST.read_text()
    captions: dict[str, str] = {}
    for src, caption in re.findall(
        r"src:\s*'([^']+)'.*?caption:\s*'((?:[^'\\]|\\.)*)'", text, re.S
    ):
        captions[Path(src).name] = caption
    return captions


def main() -> None:
    if not PHOTO_DIR.is_dir():
        raise SystemExit(f"no such directory: {PHOTO_DIR}")

    files = sorted(
        (p for p in PHOTO_DIR.iterdir() if p.suffix.lower() in EXTS),
        key=lambda p: p.name.lower(),
    )
    if not files:
        raise SystemExit(f"no images found in {PHOTO_DIR}")

    captions = existing_captions()

    entries = []
    for f in files:
        caption = captions.get(f.name)
        lines = [
            "  {",
            f"    src: '/bday2026/{f.name}',",
            "    alt: 'Us',",
        ]
        if caption:
            lines.append(f"    caption: '{caption}',")
        lines.append("  },")
        entries.append("\n".join(lines))

    MANIFEST.write_text(HEADER + "\n".join(entries) + "\n];\n")
    print(f"wrote {MANIFEST.relative_to(ROOT)} with {len(files)} photo(s)")


if __name__ == "__main__":
    main()
